#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2015 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# $FreeBSD: /src/etc/rc.d/rpcbind
# Changes: Remove useless requirements named
#

# PROVIDE: rpcbind
# REQUIRE: NETWORKING ntpdate syslogd
# KEYWORD: shutdown
# XQUERY: -i "count(//nfsd/enable) > 0" -o "0" -b
# RCVAR: rpcbind

. /etc/rc.subr

name="rpcbind"
rcvar=rpcbind_enable
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
