#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2015 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (c) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# All rights reserved.
#
# PROVIDE: system_init
# BEFORE: SYSTEMINIT

. /etc/rc.subr

name="system_init"

load_rc_config "${name}"

# Custom commands
stop_cmd=":"
start_cmd="system_init_start"

system_init_start()
{
	# If firmware.lock file exists, delete it (otherwise all WebGUI pages will be redirected to upgrade page).
	if [ -f "/var/run/firmware.lock" ]; then
		rm -f /var/run/firmware.lock
	fi

	# Start core system
	eval /etc/rc.d.php/${name}
	return $?
}

run_rc_command "$1"
