#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/cleanvar,v 1.15.2.1.2.1 2011/11/11 04:20:22 kensmith Exp $
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (C) 2012 NAS4Free Team <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (C) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# All rights reserved.
#
# ---> Change: Skip over *.hints files, otherwise 'xml' cmd fails!
#

# PROVIDE: cleanvar
# REQUIRE: FILESYSTEMS var

. /etc/rc.subr

name="cleanvar"
rcvar=`set_rcvar`

start_precmd="${name}_prestart"
start_cmd="${name}_start"
stop_cmd=":"

extra_commands="reload"
reload_cmd="${name}_start"

purgedir()
{
	local dir file

	if [ $# -eq 0 ]; then
		purgedir .
	else
		for dir
		do
		(
			cd "$dir" && for file in .* *
			do
				# Skip over logging sockets
				[ -S "$file" -a "$file" = "log" ] && continue
				[ -S "$file" -a "$file" = "logpriv" ] && continue
				[ ."$file" = .. -o ."$file" = ... ] && continue
				# Skip over *.hints files
				[ `expr \"$file\" : \".*.hints\"` -gt 0 ] && continue
				if [ -d "$file" -a ! -L "$file" ]
				then
					purgedir "$file"
				else
					rm -f -- "$file"
				fi
			done
		)
		done
	fi
}

cleanvar_prestart()
{
	# These files must be removed only the first time this script is run
	# on boot.
	#
	rm -f /var/run/clean_var /var/spool/lock/clean_var
}

cleanvar_start () 
{
	if [ -d /var/run -a ! -f /var/run/clean_var ]; then
		purgedir /var/run
		# And an initial utmp file
		(cd /var/run && cp /dev/null utmp && chmod 644 utmp)
		>/var/run/clean_var
	fi
	if [ -d /var/spool/lock -a ! -f /var/spool/lock/clean_var ]; then
		purgedir /var/spool/lock
		>/var/spool/lock/clean_var
	fi
	rm -rf /var/spool/uucp/.Temp/*
}

load_rc_config $name
run_rc_command "$1"
