#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2017 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# Execute postinit commands
#

# PROVIDE: execcmd_postinit
# REQUIRE: LOGIN

. /etc/rc.subr
. /etc/configxml.subr

if [ -x /etc/rc.d.php/postinit ]; then
	eval /etc/rc.d.php/postinit
fi

# Execute all commands.
/usr/local/bin/xml sel -t -m "//rc/postinit/cmd" \
	-v "." \
	-i "position() <= last()" -n -b \
	${configxml_file} | /usr/local/bin/xml unesc | \
	while read _cmd; do
		eval ${_cmd}
	done

# Execute all commands from config 2.8.
/usr/local/bin/xml sel -t -m "//rc/param[typeid=2 and enable]/value" \
	-v "." \
	-i "position() <= last()" -n -b \
	${configxml_file} | /usr/local/bin/xml unesc | \
	while read _cmd; do
		eval ${_cmd}
	done
