#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#

# PROVIDE: hastd
# REQUIRE: NETWORKING syslogd
# BEFORE:  DAEMON
# KEYWORD: nojail shutdown
# XQUERY: -i "count(//hast/enable) > 0" -o "0" -b
# RCVAR: hastd

. /etc/rc.subr
. /etc/util.subr
. /etc/configxml.subr

name="hastd"
rcvar="hastd_enable"
load_rc_config "${name}"

start_precmd="hastd_mkconf"
stop_precmd="hastd_stop_precmd"
extra_commands="reload mkconf"

hastd_config=${hastd_config:-"/var/etc/hast.conf"}
pidfile="/var/run/${name}.pid"
command="/sbin/${name}"
hastctl="/sbin/hastctl"
required_modules="geom_gate:g_gate"

hastd_mkconf()
{
	# Create hastd.conf file
	/usr/local/bin/xml sel -t -m "//hast" \
	    -m "auxparam" \
		-v "." -n -b \
	    ${configxml_file} | /usr/local/bin/xml unesc > ${hastd_config}
}

hastd_stop_precmd()
{
	${hastctl} role init all
}

load_rc_config $name
run_rc_command "$1"
