#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2017 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# Set the system\'s hostname
# $FreeBSD: /etc/rc.d/hostname		Revision 298514
#

# PROVIDE: hostname
# REQUIRE: FILESYSTEMS
# BEFORE:  netif

. /etc/rc.subr
. /etc/network.subr

name="hostname"
desc="Set the system\'s hostname"
start_cmd="hostname_start"
restart_cmd="hostname_restart"
stop_cmd=":"

hostname_start()
{
	# If we are not inside a jail, set the host name.
	# If we are inside a jail, set the host name if it is permitted.
	#
	if [ `$SYSCTL_N security.jail.jailed` -eq 1 ]; then
		if [ `$SYSCTL_N security.jail.set_hostname_allowed` -eq 0 ]; then
			return
		fi
	else
		# If we're not in a jail and rc.conf doesn't specify a
		# hostname, see if we can get one from kenv.
		#
		if [ -z "${hostname}" -a \
		    -n "`/bin/kenv dhcp.host-name 2> /dev/null`" ]; then
			hostname=`/bin/kenv dhcp.host-name`
		fi
	fi

	# Have we got a hostname yet?
	#
	if [ -z "${hostname}" ]; then
		# Null hostname is probably OK if DHCP is in use.
		#
		if [ -z "`list_net_interfaces dhcp`" ]; then
			warn "\$hostname is not set -- see rc.conf(5)."
		fi
		return
	fi

	# All right, it is safe to invoke hostname(1) now.
	#
	[ -z "${rc_quiet}" ] && echo "Setting hostname: ${hostname}."
	/bin/hostname "${hostname}"
}

hostname_restart()
{
	# Reset hostname
	/bin/hostname ""
	run_rc_command start
}

load_rc_config $name
run_rc_command "$1"
