#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2017 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# Deamon iscsi_initiator

# PROVIDE: iscsi_initiator
# REQUIRE: NETWORKING netwait
# BEFORE: mountcritremote
# KEYWORD: shutdown
# XQUERY: -i "count(//iscsiinit/vdisk) > 0" -o "0" -b
# RCVAR: iscsi_initiator

. /etc/rc.subr
. /etc/configxml.subr

name="iscsi_initiator"
desc="Deamon iscsi_initiator"
rcvar=iscsi_initiator_enable

load_rc_config "$name"

# Custom commands
mkconf_cmd="iscsi_initiator_mkconf"
start_precmd="iscsi_initiator_prestart"
start_cmd="iscsi_initiator_start"
stop_cmd="iscsi_initiator_stop"
extra_commands="mkconf"

# Defaults
iscsi_initiator_enable="${iscsi_initiator_enable:=NO}"
#command="/sbin/iscontrol"
command="/usr/bin/iscsictl"
iscsi_initiator_conf="/etc/iscsi.conf"

iscsi_initiator_mkconf()
{
	cat /dev/null > ${iscsi_initiator_conf}
	chmod 600 ${iscsi_initiator_conf}

	/usr/local/bin/xml sel -t -m "//iscsiinit/vdisk" \
		-v "concat(normalize-space(name), ' {')" -n \
		-v "concat('	targetaddress = ', targetaddress)" -n \
		-v "concat('	targetname = ', targetname)" -n \
		-v "concat('	initiatorname = ', initiatorname)" -n \
		-o "}" -n \
		-i "position() <= last()" -n -b \
		${configxml_file} | /usr/local/bin/xml unesc >> ${iscsi_initiator_conf}
}

iscsi_initiator_prestart()
{
	iscsi_initiator_mkconf

	# Load kernel module
	#load_kld -e iscsi_initiator -m iscsi_initiator iscsi_initiator.ko

	# Disable debugging
	#/sbin/sysctl debug.iscsi_initiator=0 > /dev/null

	if [ -z "`pgrep iscsid`" ]; then
		/etc/rc.d/iscsid onestart
	fi
}

iscsi_initiator_start()
{
	local _command_args

	echo "Starting ${name}."

	# Iterate over all configured disks
	#/usr/local/bin/xml sel -t -m "//iscsiinit/vdisk" \
	#	-v "concat('targetaddress=',targetaddress,' targetname=',targetname,' initiatorname=',initiatorname)" \
	#	-i "position() <= last()" -n -b \
	#	${configxml_file} | /usr/local/bin/xml unesc | \
	#	while read _command_args; do
	#		eval ${command} ${_command_args}
	#	done

	# Add all targets
	eval ${command} -Aa
}

iscsi_initiator_stop()
{
	echo "Stopping ${name}."
	#/usr/bin/killall -HUP iscontrol > /dev/null 2>&1

	#retry=20
	#echo "Wait for iSCSI session end"
	#while [ $retry -ne 0 ]; do
	#	num=`/sbin/sysctl -q -n net.iscsi_initiator.sessions`
	#	[ -z "$num" ] && break;
	#	[ $num -eq 0 ] && break;
	#	echo -n "."
	#	sleep 1
	#	retry=`/bin/expr $retry - 1`
	#done
	#if [ $retry -eq 0 ]; then
	#	echo ".Give up"
	#else
	#	echo ".OK"
	#fi

	# Remove all targets
	eval ${command} -Ra
}

run_rc_command "$1"
