#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (c) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# All rights reserved.
#

# PROVIDE: iscsi_initiator
# REQUIRE: NETWORKING netwait
# BEFORE: mountcritremote
# KEYWORD: shutdown
# XQUERY: -i "count(//iscsiinit/vdisk) > 0" -o "0" -b
# RCVAR: iscsi_initiator

. /etc/rc.subr
. /etc/configxml.subr

name="iscsi_initiator"
rcvar=`set_rcvar`

load_rc_config "$name"

# Custom commands
start_precmd="iscsi_initiator_prestart"
start_cmd="iscsi_initiator_start"
stop_cmd="iscsi_initiator_stop"

# Defaults
iscsi_initiator_enable="${iscsi_initiator_enable:=NO}"
command="/sbin/iscontrol"

iscsi_initiator_prestart()
{
	# Load kernel module
	load_kld -e iscsi_initiator -m iscsi_initiator iscsi_initiator.ko

	# Disable debugging
	/sbin/sysctl debug.iscsi_initiator=0 > /dev/null
}

iscsi_initiator_start()
{
	local _command_args

	echo "Starting ${name}."

	# Iterate over all configured disks
	/usr/local/bin/xml sel -t -m "//iscsiinit/vdisk" \
		-v "concat('targetaddress=',targetaddress,' targetname=',targetname,' initiatorname=',initiatorname)" \
		-i "position() != last()" -n -b \
		${configxml_file} | /usr/local/bin/xml unesc | \
		while read _command_args; do
			eval ${command} ${_command_args}
		done
}

iscsi_initiator_stop()
{
	echo "Stopping ${name}."
	/usr/bin/killall -HUP iscontrol > /dev/null 2>&1

	retry=20
	echo "Wait for iSCSI session end"
	while [ $retry -ne 0 ]; do
		num=`/sbin/sysctl -q -n net.iscsi_initiator.sessions`
		[ $num -eq 0 ] && break;
		echo -n "."
		sleep 1
		retry=`/bin/expr $retry - 1`
	done
	if [ $retry -eq 0 ]; then
		echo ".Give up"
	else
		echo ".OK"
	fi
}

run_rc_command "$1"
