#!/bin/sh
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (C) 2012 NAS4Free Team <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (C) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# All rights reserved.
#

# PROVIDE: motd
# REQUIRE: mountcritremote
# BEFORE: LOGIN

. /etc/rc.subr
. /etc/configxml.subr

name="motd"

load_rc_config "$name"

# Defaults
motd_config=${motd_config:-"/etc/motd"}

echo "Generating message of the day."

# Create the /etc/motd file
/usr/local/bin/xml sel -t \
	-v //system/motd \
	 ${configxml_file} | /usr/local/bin/xml unesc > ${motd_config}.tmp
/usr/bin/uudecode -m -p -r ${motd_config}.tmp > ${motd_config}
/bin/rm -f ${motd_config}.tmp
