#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2017 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# Message of the day
#

# PROVIDE: motd
# REQUIRE: mountcritremote
# BEFORE: LOGIN

. /etc/rc.subr
. /etc/configxml.subr

name="motd"
desc="Update /etc/motd"
load_rc_config "$name"

# Defaults
motd_config=${motd_config:-"/etc/motd"}

echo "Generating message of the day."

# Create the /etc/motd file
/usr/local/bin/xml sel -t \
	-v //system/motd \
	 ${configxml_file} | /usr/local/bin/xml unesc > ${motd_config}.tmp
/usr/bin/uudecode -m -p -r ${motd_config}.tmp > ${motd_config}
/bin/rm -f ${motd_config}.tmp
