#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2017 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#

# PROVIDE: netfix
# REQUIRE: netif devd
# BEFORE: NETWORKING

. /etc/rc.subr
. /etc/configxml.subr

check_member()
{
	local _bridge _member _request _if _m _found

	_bridge=$1
	_member=`ifconfig "${_bridge}" | awk '/^.+member:/ { print $2 }'`
	_request=`sysrc -n "ifconfig_${_bridge}" | awk '{while(match($0,/addm[[:space:]]+[^[:space:]]+/)){t=substr($0,RSTART,RLENGTH);sub("addm[[:space:]]+", "", t);print t;$0=substr($0,RSTART+RLENGTH)}}'`

	debug "check member: $_bridge"
	# check all member
	for _if in $_request; do
		_found=0
		for _m in $_member; do
			if [ "$_m" = "$_if" ]; then
				_found=1
				break
			fi
		done
		if [ $_found -eq 0 ]; then
			debug "not member: $_if"
			return 1
		fi
	done
	return 0
}

netfix_bridge_restart()
{
	local _if

	# restart bridge with USB device provided by devd
	/usr/local/bin/xml sel -t \
		-m "//vinterfaces/bridge" \
			-v if \
			-n \
		-b \
		${configxml_file} | /usr/local/bin/xml unesc | \
		while read _if; do \
			if [ -n "$_if" ]; then
				if check_member $_if; then
					continue
				fi
				echo "Restarting $_if"
				/etc/rc.d/netif restart "$_if"
			fi
		done
}

netfix_bridge_restart
