#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2017 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# $FreeBSD: src/etc/rc.d/NETWORKING
# Changes: added REQUIRE: resolv, Removed REQUIRE: ppp ipfw stf faith REQUIRE: static_arp static_ndp
#

# PROVIDE: NETWORKING NETWORK
# REQUIRE: CONFIG
# REQUIRE: netif netoptions routing
# REQUIRE: resolv

#	This is a dummy dependency, for services which require networking
#	to be operational before starting.
