#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2017 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# timezone
#

# PROVIDE: timezone
# BEFORE: CONFIG
# REQUIRE: SYSTEMINIT

. /etc/rc.subr
. /etc/configxml.subr

_timezone=`configxml_get "//system/timezone"`
if [ -z "${_timezone}" ]; then
	_timezone="Etc/UTC"
fi

/usr/bin/tar -xOf /usr/share/zoneinfo.txz "./${_timezone}" > /etc/localtime
