#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2015 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (c) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# All rights reserved.
#

# PROVIDE: userdb
# BEFORE: CONFIG
# REQUIRE: SYSTEMINIT

. /etc/rc.subr
. /etc/configxml.subr

name="userdb"

load_rc_config "$name"

# Defaults
userdb_group=${userdb_group:-"/etc/group"}
userdb_passwd=${userdb_passwd:-"/etc/passwd"}
userdb_masterpasswd=${userdb_masterpasswd:-"/etc/master.passwd"}

echo "Generating user database(s)."

# Create the /etc/group file
/usr/local/bin/xml sel -t \
	-o "wheel:*:0:root" -n \
	-o "daemon:*:1:" -n \
	-o "kmem:*:2:" -n \
	-o "sys:*:3:" -n \
	-o "tty:*:4:" -n \
	-o "operator:*:5:root" -n \
	-o "mail:*:6:" -n \
	-o "bin:*:7:" -n \
	-o "news:*:8:" -n \
	-o "man:*:9:" -n \
	-o "games:*:13:" -n \
	-o "staff:*:20:" -n \
	-o "sshd:*:22:" -n \
	-o "smmsp:*:25:" -n \
	-o "mailnull:*:26:" -n \
	-o "guest:*:31:" -n \
	-o "bind:*:53:" -n \
	-o "unbound:*:59:" -n \
	-o "proxy:*:62:" -n \
	-o "authpf:*:63:" -n \
	-o "_pflogd:*:64:" -n \
	-o "_dhcp:*:65:" -n \
	-o "uucp:*:66:" -n \
	-o "dialer:*:68:" -n \
	-o "network:*:69:" -n \
	-o "audit:*:77:" -n \
	-o "www:*:80:" -n \
	-o "hast:*:845:" -n \
	-o "nogroup:*:65533:" -n \
	-o "nobody:*:65534:" -n \
	-o "ftp:*:50:" -n \
	-m "//system/usermanagement/group" \
		-v "concat(name,':*:',id,':')" -n \
	-b \
	-m "//access/group" \
		-v "concat(name,':*:',id,':')" -n \
	-b \
	 ${configxml_file} | /usr/local/bin/xml unesc > ${userdb_group}

# Clean /etc/passwd file
cat /dev/null > ${userdb_passwd}

# Encrypt password
_password=`configxml_get "//system/password"`
_password_md5=`/usr/sbin/mkpw -e md5 "${_password}"`
_password_sha=`configxml_get "//system/password"`

# Create the /etc/master.passwd file
echo "root:${_password_sha}:0:0::0:0:Charlie &:/root:/bin/tcsh
toor:*:0:0::0:0:Bourne-again Superuser:/root:
daemon:*:1:1::0:0:Owner of many system processes:/root:/usr/sbin/nologin
operator:*:2:5::0:0:System &:/:/usr/sbin/nologin
bin:*:3:7::0:0:Binaries Commands and Source:/:/usr/sbin/nologin
tty:*:4:65533::0:0:Tty Sandbox:/:/usr/sbin/nologin
kmem:*:5:65533::0:0:KMem Sandbox:/:/usr/sbin/nologin
games:*:7:13::0:0:Games pseudo-user:/usr/games:/usr/sbin/nologin
news:*:8:8::0:0:News Subsystem:/:/usr/sbin/nologin
man:*:9:9::0:0:Mister Man Pages:/usr/share/man:/usr/sbin/nologin
sshd:*:22:22::0:0:Secure Shell Daemon:/var/empty:/usr/sbin/nologin
smmsp:*:25:25::0:0:Sendmail Submission User:/var/spool/clientmqueue:/usr/sbin/nologin
mailnull:*:26:26::0:0:Sendmail Default User:/var/spool/mqueue:/usr/sbin/nologin
bind:*:53:53::0:0:Bind Sandbox:/:/usr/sbin/nologin
unbound:*:59:59::0:0:Unbound DNS Resolver:/var/empty:/usr/sbin/nologin
proxy:*:62:62::0:0:Packet Filter pseudo-user:/nonexistent:/usr/sbin/nologin
_pflogd:*:64:64::0:0:pflogd privsep user:/var/empty:/usr/sbin/nologin
_dhcp:*:65:65::0:0:dhcp programs:/var/empty:/usr/sbin/nologin
pop:*:68:6::0:0:Post Office Owner:/nonexistent:/usr/sbin/nologin
www:*:80:80::0:0:World Wide Web Owner:/nonexistent:/usr/sbin/nologin
hast:*:845:845::0:0:HAST unprivileged user:/var/empty:/usr/sbin/nologin
nobody:*:65534:65534::0:0:Unprivileged user:/nonexistent:/usr/sbin/nologin
ftp:*:21:50::0:0:FTP user:/mnt:/sbin/nologin
uucp:*:66:66::0:0:UUCP pseudo-user:/var/empty:/usr/sbin/nologin" > ${userdb_masterpasswd}

# Generate the /etc/passwd, pwd.db and spwd.db files
/usr/sbin/pwd_mkdb -p ${userdb_masterpasswd} > /dev/null 2>&1

# Add system users
_index=`configxml_get_count "//system/usermanagement/user"`
while [ ${_index} -gt 0 ]
do
	_cmdarg=`/usr/local/bin/xml sel -t -m "//system/usermanagement/user[${_index}]" \
		-v "concat('-n ',name,' -u ',id,' -g ',primarygroup)" \
		-i "count(group) > 0" -o " -G " -b \
		-m "group" \
			-i "position() > 1" -o "," -b \
			-v "." \
		-b \
		-i "string-length(extraoptions) > 0" -v "concat(' ',extraoptions)" -b \
		${configxml_file} | /usr/local/bin/xml unesc`

	eval "/usr/sbin/pw user add -q ${_cmdarg} > /dev/null"

	_index=$(( ${_index} - 1 ))
done

# Add configured users
_index=`configxml_get_count "//access/user"`
while [ ${_index} -gt 0 ]
do
	_cmdarg=`/usr/local/bin/xml sel -t -m "//access/user[${_index}]" \
		-v "concat('-n ',login,' -u ',id,' -g ',primarygroup,' -c \"',fullname,'\"')" \
		-i "count(group) > 0" -o " -G " -b \
		-m "group" \
			-i "position() > 1" -o "," -b \
			-v "." \
		-b \
		-i "string-length(shell) > 0" -v "concat(' -s ',shell)" -b \
		-i "string-length(shell) = 0" -o " -s nologin" -b \
		-i "string-length(homedir) = 0" -o " -d /mnt" -b \
		-i "string-length(homedir) > 0" \
			-i "homedir[.!='/mnt']" -o " -m " -b \
			-v "concat(' -d ',homedir)" -b \
		-i "string-length(password) > 0" -o " -h 0" -b \
		${configxml_file} | /usr/local/bin/xml unesc`

	_userpasswd=`configxml_get "//access/user[${_index}]/password"`

	eval "(/bin/echo '${_userpasswd}') | /usr/sbin/pw user add -q ${_cmdarg} > /dev/null"

	_index=$(( ${_index} - 1 ))
done
