#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2017 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# Populate /var directory
#
# $FreeBSD: /etc/rc.d/var	revision 299839
# Changes: - Remove useless code
#    ToDo: - Relocate code to populate /var from /etc/rc to this file ASAP
#

# PROVIDE: var
# REQUIRE: mountcritlocal

# NFS /var is not supported, unless NFS /var is part of diskless NFS /

. /etc/rc.subr

name="var"
desc="Populate /var directory"
stop_cmd=':'

load_rc_config $name

populate_var()
{
	# Create required directories in /var
	/usr/sbin/mtree -deiU -f /etc/mtree/BSD.var.dist -p /var > /dev/null
	# Configure the shared library cache
	/sbin/ldconfig -elf /usr/lib /usr/local/lib /lib
}

# If we do not have a writable /var, create a memory filesystem for /var
# unless told otherwise by rc.conf.  We don't have /usr yet so use mkdir
# instead of touch to test.  We want mount to record its mounts so we
# have to make sure /var/db exists before doing the mount -a.
#
BOOT_LOWMEM=0
if [ -f /etc/boot_lowmem ]; then
	BOOT_LOWMEM=`/bin/cat /etc/boot_lowmem`
fi
PLATFORM=`/bin/cat /etc/platform`
case "${varmfs}" in
[Yy][Ee][Ss])
	if [ ${BOOT_LOWMEM} -ne 0 ]; then
		mount_md ${varsize} /var "${varmfs_flags}"
	else
		case ${PLATFORM} in
		*-embedded)
			mount_md ${varsize} /var "${varmfs_flags}"
			;;
		*)
			mount_md ${varsize} /var "${varmfs_flags}"
			;;
		esac
	fi
	mkdir /var/tmp
	/sbin/mount -t tmpfs -o mode=1777,size=${vartmpsize} tmpfs /var/tmp
	;;
[Nn][Oo])
	;;
*)
	if /bin/mkdir -p /var/.diskless 2> /dev/null; then
		rmdir /var/.diskless
	else
		if [ ${BOOT_LOWMEM} -ne 0 ]; then
			mount_md ${varsize} /var "${varmfs_flags}"
		else
			case ${PLATFORM} in
			*-embedded)
				mount_md ${varsize} /var "${varmfs_flags}"
				;;
			*)
				mount_md ${varsize} /var "${varmfs_flags}"
				;;
			esac
		fi
		mkdir /var/tmp
		/sbin/mount -t tmpfs -o mode=1777,size=${vartmpsize} tmpfs /var/tmp
	fi
esac


# If we have an empty looking /var, populate it, but only if we have
# /usr available.  Hopefully, we'll eventually find a workaround, but
# in realistic diskless setups, we're probably ok.
case "${populate_var}" in
[Yy][Ee][Ss])
	populate_var
	;;
[Nn][Oo])
	;;
*)
	if [ -d /var/run -a -d /var/db -a -d /var/empty ] ; then
		true
	else
		if [ ! -x /usr/sbin/mtree ] ; then
			exit 1
		fi
		populate_var
	fi
	;;
esac

# Make sure we have /var/log/utx.lastlogin and /var/log/utx.log files
if [ ! -f /var/log/utx.lastlogin ]; then
	cp /dev/null /var/log/utx.lastlogin
	chmod 644 /var/log/utx.lastlogin
fi
if [ ! -f /var/log/utx.log ]; then
	cp /dev/null /var/log/utx.log
	chmod 644 /var/log/utx.log
fi
