#!/usr/local/bin/php -f
<?php
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (C) 2012 NAS4Free Team <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (C) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# Copyright (c) 2007 Volker Theile <votdev@gmx.de>.
# All rights reserved.
require_once("report.inc");

$retval = @report_send_mail();
exit($retval);
?>
