#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (c) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# All rights reserved.
#

# PROVIDE: beep
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr
. /etc/configxml.subr

name="beep"

# Custom commands
start_cmd="beep_start"
stop_cmd="beep_stop"

beep_start()
{
	if ! configxml_isset //system/disablebeep; then
		if [ -e /dev/speaker ]; then
			echo O3L30cO4L30cO5L30cO5L30g > /dev/speaker
		fi
	fi
}

beep_stop()
{
	if ! configxml_isset //system/disablebeep; then
		if [ -e /dev/speaker ]; then
			echo O5L30gO5L30cO4L30cO3L30c > /dev/speaker
		fi
	fi
}

run_rc_command "$1"
