#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/bgfsck,v 1.10.2.1.2.1 2011/11/11 04:20:22 kensmith Exp $
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (C) 2012 NAS4Free Team <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (C) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# Modified by Volker Theile <votdev@gmx.de>
# Modified by Michael Zoon <zoon01@nas4free.org>
# All rights reserved.
#

# PROVIDE: bgfsck
# REQUIRE: cron syslogd
# KEYWORD: nojail

. /etc/rc.subr
. /etc/configxml.subr

name="background-fsck"
rcvar="background_fsck"
start_cmd="bgfsck_start"
stop_cmd=":"

bgfsck_start ()
{
	if [ -z "${rc_force}" ]; then
		background_fsck_delay=${background_fsck_delay:=0}
	else
		background_fsck_delay=0
	fi
	if [ ${background_fsck_delay} -lt 0 ]; then
		echo "Background file system checks delayed indefinitely"
		return 0
	fi

	bgfsck_msg='Starting background file system checks'
	if [ "${background_fsck_delay}" -gt 0 ]; then
		bgfsck_msg="${bgfsck_msg} in ${background_fsck_delay} seconds"
	fi
	if [ -z "${rc_force}" ]; then
		check_startmsgs && echo "${bgfsck_msg}."
	fi

	/usr/local/bin/xml sel -t -m "//mounts/mount[fstype = 'ufs' or fstype = 'msdosfs' or fstype = 'ext2fs']" \
		-v "concat(fstype,' ',devicespecialfile,' ',mdisk)" \
		-i "count(fsck) > 0" -o " 1" -b \
		-i "count(fsck) = 0" -o " 0" -b \
		-i "position() != last()" -n -b \
		${configxml_file} | /usr/local/bin/xml unesc | \
	while read _fstype _devicespecialfile _mdisk _fsck; do
		# Check if fsck is enabled
		if [ "0" = "${_fsck}" ]; then
			continue
		fi

		# Check if block device exists
		if [ ! -e "${_devicespecialfile}" ]; then
			continue
		fi

		# Skip encrypted disks
		_encrypted=`configxml_get_count "//geli/vdisk[devicespecialfile = '${_mdisk}']"`
		if [ 0 -lt ${_encrypted} ]; then
			continue
		fi

		(sleep ${background_fsck_delay}; nice -4 fsck -B -p -t ${_fstype} ${_devicespecialfile}) 2>&1 | \
			logger -p daemon.notice -t fsck &
	done
}

load_rc_config $name
run_rc_command "$1"
