#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2015 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (c) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# All rights reserved.
#
# $FreeBSD: src/etc/rc.d/lockd
# Changes:	- Remove nfsclient
#

# PROVIDE: lockd
# REQUIRE: nfsd rpcbind statd
# BEFORE:  DAEMON
# KEYWORD: nojail shutdown
# XQUERY: -i "count(//nfsd/enable) > 0" -o "0" -b
# RCVAR: rpc_lockd nfs_server

. /etc/rc.subr

name="lockd"
rcvar=rpc_lockd_enable
command="/usr/sbin/rpc.${name}"
start_precmd='lockd_precmd'
stop_precmd='checkyesno nfs_server_enable || checkyesno nfs_client_enable'
status_precmd=$stop_precmd

# Make sure that we are either an NFS client or server, and that we get
# the correct flags from rc.conf(5).
#
lockd_precmd()
{
	local ret
	ret=0

	if ! checkyesno nfs_server_enable && ! checkyesno nfs_client_enable
	then
		ret=1
	fi
	if ! checkyesno rpcbind_enable && \
	    ! /etc/rc.d/rpcbind forcestatus 1>/dev/null 2>&1
	then
		force_depend rpcbind || ret=1
	fi
	rc_flags=${rpc_lockd_flags}
	return ${ret}
}

load_rc_config $name
run_rc_command $1
