#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2015 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#

# PROVIDE: netfix
# REQUIRE: netif devd
# BEFORE: NETWORKING

. /etc/rc.subr
. /etc/configxml.subr

netfix_bridge_restart()
{
	local _if

	# restart bridge with USB device provided by devd
	/usr/local/bin/xml sel -t \
		-m "//vinterfaces/bridge" \
			-v if \
			-n \
		-b \
		${configxml_file} | /usr/local/bin/xml unesc | \
		while read _if; do \
			if [ -n "$_if" ]; then
				/etc/rc.d/netif restart "$_if"
			fi
		done
}

netfix_bridge_restart
