#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/nfscbd,v 1.1.4.1.2.1 2011/11/11 04:20:22 kensmith Exp $
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (c) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# All rights reserved.
#

# PROVIDE: nfscbd
# REQUIRE: NETWORKING
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="nfscbd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
sig_stop="USR1"

load_rc_config $name

run_rc_command "$1"

