#!/bin/sh
#
# Copyright (c) 1993 - 2004 The FreeBSD Project. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $FreeBSD: src/etc/rc.d/nsswitch,v 1.15.2.1.2.1 2011/11/11 04:20:22 kensmith Exp $
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (C) 2012 NAS4Free Team <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (C) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# All rights reserved.
#
# Changes:	- Add 'var' as requirement
# 		- Add code to create configuration file from config.xml
#

# PROVIDE: nsswitch
# REQUIRE: root var
# BEFORE: NETWORK

. /etc/rc.subr
. /etc/configxml.subr

name="nsswitch"
start_cmd="nsswitch_start"
start_precmd="generate_nsswitch_conf"
stop_cmd=":"

generate_nsswitch_conf()
{
	/usr/local/bin/xml sel -t \
		-i "count(//ad/enable) > 0" -i "count(//ldap/enable) = 0" \
			-o "group: files winbind" -n \
			-o "group_compat: nis" -n \
			-o "hosts: files dns" -n \
			-o "networks: files" -n \
			-o "passwd: files winbind" -n \
		-b -b \
		-i "count(//ad/enable) > 0" -i "count(//ldap/enable) > 0" \
			-o "group: files winbind ldap" -n \
			-o "group_compat: nis" -n \
			-o "hosts: files dns" -n \
			-o "networks: files" -n \
			-o "passwd: files winbind ldap" -n \
		-b -b \
		-i "count(//ad/enable) = 0" -i "count(//ldap/enable) > 0" \
			-o "group: files ldap" -n \
			-o "group_compat: nis" -n \
			-o "hosts: files dns" -n \
			-o "networks: files" -n \
			-o "passwd: files ldap" -n \
		-b -b \
		-i "count(//ad/enable) = 0" -i "count(//ldap/enable) = 0" \
			-o "group: compat" -n \
			-o "group_compat: nis" -n \
			-o "hosts: files dns" -n \
			-o "networks: files" -n \
			-o "passwd: compat" -n \
		-b -b \
		-o "passwd_compat: nis" -n \
		-o "shells: files" -n \
		-o "services: compat" -n \
		-o "services_compat: nis" -n \
		-o "protocols: files" -n \
		-o "rpc: files" \
		${configxml_file} | /usr/local/bin/xml unesc > /etc/nsswitch.conf
}

generate_host_conf()
{
    local _cont _sources

    nsswitch_conf=$1; shift;
    host_conf=$1; shift;

  _cont=0
    _sources=""
    while read line; do
	line=${line##[ 	]}
	case $line in
	hosts:*)
		;;
	*)
		if [ $_cont -ne 1 ]; then
			continue
		fi
		;;
	esac
	if [ "${line%\\}" = "${line}\\" ]; then
		_cont=1
	fi
	line=${line#hosts:}
	line=${line%\\}
	line=${line%%#*}
	_sources="${_sources}${_sources:+ }$line"
    done < $nsswitch_conf

    echo "# Auto-generated from nsswitch.conf" > $host_conf
    for _s in ${_sources}; do
	case $_s in
	files)
		echo "hosts" >> $host_conf
		;;
	dns)
		echo "dns" >> $host_conf
		;;
	nis)
		echo "nis" >> $host_conf
		;;
	*=*)
		;;
	*)
		printf "Warning: unrecognized source [%s]", $_s > "/dev/stderr"
		;;
	esac
    done
}

nsswitch_start()
{
	# Generate host.conf for compatibility
	#
	if [ ! -f "/etc/host.conf" -o \
		"/etc/host.conf" -ot "/etc/nsswitch.conf" ]
	then
		echo 'Generating host.conf.'
		generate_host_conf /etc/nsswitch.conf /etc/host.conf
	fi

}

load_rc_config $name
run_rc_command "$1"
