#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/SERVERS,v 1.9.2.1.2.1 2011/11/11 04:20:22 kensmith Exp $
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2013 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (c) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# All rights reserved.
#

# PROVIDE: SERVERS
# REQUIRE: mountcritremote

#	This is a dummy dependency, for early-start servers relying on
#	some basic configuration.
