#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2015 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (c) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# All rights reserved.
#
# $FreeBSD: src/etc/rc.d/wpa_supplicant
#

# PROVIDE: wpa_supplicant
# REQUIRE: mountcritremote
# KEYWORD: nojail nostart
# XQUERY: -i "count(//interfaces/*/wpa/enable) > 0" -o "0" -b
# RCVAR: wpa_supplicant

. /etc/rc.subr
. /etc/network.subr
. /etc/configxml.subr

name="wpa_supplicant"
rcvar=

ifn="$2"
if [ -z "$ifn" ]; then
	return 1
fi

is_ndis_interface()
{
	case `sysctl -n net.wlan.${1#wlan}.%parent 2>/dev/null` in
		ndis*) true ;;
		*) false ;;
	esac
}

if is_wired_interface ${ifn} ; then
	driver="wired"
elif is_ndis_interface ${ifn} ; then
	driver="ndis"
else
	driver="bsd"
fi

# Create wpa_supplicant.conf
/usr/local/bin/xml sel -t -m "//interfaces/*/wireless/wpa[enable]" \
	-o "network={" -n \
	-v "concat('ssid=\"',../ssid,'\"')" -n \
	-v "concat('key_mgmt=',keymgmt)" -n \
	-v "concat('pairwise=',pairwise)" -n \
	-v "concat('group=',pairwise)" -n \
	-v "concat('psk=\"',psk,'\"')" -n \
	-o "}" -n \
	${configxml_file} | /usr/local/bin/xml unesc > ${conf_file}

load_rc_config $name

command=${wpa_supplicant_program}
conf_file=${wpa_supplicant_conf_file}
pidfile="/var/run/${name}/${ifn}.pid"
command_args="-B -i $ifn -c $conf_file -D $driver -P $pidfile"
required_files=$conf_file
required_modules="wlan_wep wlan_tkip wlan_ccmp"

run_rc_command "$1"
