#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2015 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (c) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# All rights reserved.
#
# $FreeBSD: src/etc/rc.d/nsswitch
# Changes:	- Add 'var' as requirement
# 		- Add code to create configuration file from config.xml
#

# PROVIDE: nsswitch
# REQUIRE: root var
# BEFORE: NETWORK

. /etc/rc.subr
. /etc/configxml.subr

name="nsswitch"
start_cmd="nsswitch_start"
start_precmd="generate_nsswitch_conf"
stop_cmd=":"

generate_nsswitch_conf()
{
	/usr/local/bin/xml sel -t \
		-i "count(//ad/enable) > 0" -i "count(//ldap/enable) = 0" \
			-o "group: files winbind" -n \
			-o "group_compat: nis" -n \
			-o "hosts: files dns" -n \
			-o "networks: files" -n \
			-o "passwd: files winbind" -n \
		-b -b \
		-i "count(//ad/enable) > 0" -i "count(//ldap/enable) > 0" \
			-o "group: files winbind ldap" -n \
			-o "group_compat: nis" -n \
			-o "hosts: files dns" -n \
			-o "networks: files" -n \
			-o "passwd: files winbind ldap" -n \
		-b -b \
		-i "count(//ad/enable) = 0" -i "count(//ldap/enable) > 0" \
			-o "group: files ldap" -n \
			-o "group_compat: nis" -n \
			-o "hosts: files dns" -n \
			-o "networks: files" -n \
			-o "passwd: files ldap" -n \
		-b -b \
		-i "count(//ad/enable) = 0" -i "count(//ldap/enable) = 0" \
			-o "group: compat" -n \
			-o "group_compat: nis" -n \
			-o "hosts: files dns" -n \
			-o "networks: files" -n \
			-o "passwd: compat" -n \
		-b -b \
		-o "passwd_compat: nis" -n \
		-o "shells: files" -n \
		-o "services: compat" -n \
		-o "services_compat: nis" -n \
		-o "protocols: files" -n \
		-o "rpc: files" -n \
		${configxml_file} | /usr/local/bin/xml unesc > /etc/nsswitch.conf
}

generate_host_conf()
{
    local _cont _sources

    nsswitch_conf=$1; shift;
    host_conf=$1; shift;

    _cont=0
    _sources=""
    while read line; do
	line=${line##[ 	]}
	case $line in
	hosts:*)
		;;
	*)
		if [ $_cont -ne 1 ]; then
			continue
		fi
		;;
	esac
	if [ "${line%\\}" = "${line}\\" ]; then
		_cont=1
	fi
	line=${line#hosts:}
	line=${line%\\}
	line=${line%%#*}
	_sources="${_sources}${_sources:+ }$line"
    done < $nsswitch_conf

    echo "# Auto-generated from nsswitch.conf" > $host_conf
    for _s in ${_sources}; do
	case $_s in
	files)
		echo "hosts" >> $host_conf
		;;
	dns)
		echo "dns" >> $host_conf
		;;
	nis)
		echo "nis" >> $host_conf
		;;
	cache | *=*)
		;;
	*)
		echo "Warning: unrecognized source [$_s]" >&2
		;;
	esac
    done
}

nsswitch_start()
{
	# Generate host.conf for compatibility
	#
	if [ ! -f "/etc/host.conf" -o \
		"/etc/host.conf" -ot "/etc/nsswitch.conf" ]
	then
		echo 'Generating host.conf.'
		generate_host_conf /etc/nsswitch.conf /etc/host.conf
	fi

}

load_rc_config $name
run_rc_command "$1"
