#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2015 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#

# PROVIDE: SERVERS
# REQUIRE: mountcritremote

#	This is a dummy dependency, for early-start servers relying on
#	some basic configuration.
