#!/bin/sh
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (C) 2012 NAS4Free Team <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (C) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# Copyright (c) 2007-2009 Volker Theile <votdev@gmx.de>.
# All rights reserved.
#


# PROVIDE: timezone
# BEFORE: CONFIG
# REQUIRE: SYSTEMINIT

. /etc/rc.subr
. /etc/configxml.subr

_timezone=`configxml_get "//system/timezone"`
if [ -z "${_timezone}" ]; then
	_timezone="Etc/UTC"
fi

/usr/bin/tar -xOf /usr/share/zoneinfo.tgz "./${_timezone}" > /etc/localtime
