#!/bin/sh
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (C) 2012 NAS4Free Team <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (C) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# Copyright (c) 2007-2009 Volker Theile <votdev@gmx.de>.
# All rights reserved.
#

# PROVIDE: rsync_local
# REQUIRE: DAEMON
# BEFORE: cron

. /etc/rc.subr
. /etc/configxml.subr

name="rsync_local"

load_rc_config "$name"

# Defaults
rsync_local_logfile=${rsync_local_logfile:-"/var/log/${name}.log"}
rsync_local_logfile_mode=${rsync_local_logfile_mode:-"0666"}

# Get number of scripts to generate
_scriptnum=`configxml_get_count "//rsync/rsynclocal"`

# Generate scripts
if [ 0 -lt ${_scriptnum} ]; then
	echo "Generating local rsyncd cron scripts."

	while [ ${_scriptnum} -gt 0 ]
	do
		_uuid=`configxml_get "//rsync/rsynclocal[${_scriptnum}]/uuid"`
		_rsyncscript=/var/run/rsync_local_${_uuid}.sh
		_rsyncflag=/var/run/rsync_local_running_${_uuid}
		_who=`configxml_get "//rsync/rsynclocal[${_scriptnum}]/who"`

		# Generate the shell script that is used by cron
		/usr/local/bin/xml sel -t -m "//rsync/rsynclocal[position()=${_scriptnum}]" \
			-o "#!/bin/sh" -n \
			-v "concat('/usr/bin/logger -p local4.notice \"Start of local RSYNC from ',source,' to ',destination,'\"')" -n \
			-o "if [ -r ${_rsyncflag} ]; then" -n \
			-o "/usr/bin/logger -p local4.notice \"Previous local synchronization still running... exiting\"" -n \
			-o "exit" -n \
			-o "fi" -n \
			-o "/usr/bin/touch ${_rsyncflag}" -n \
			-o "/usr/local/bin/rsync --log-file=${rsync_local_logfile} " \
			-m "options" \
				-i "count(recursive) > 0" -o "--recursive " -b \
				-i "count(times) > 0" -o "--times " -b \
				-i "count(compress) > 0" -o "--compress " -b \
				-i "count(archive) > 0" -o "--archive " -b \
				-i "count(delete) > 0" -o "--delete " \
					-i "delete_algorithm[. != 'default']" -v "concat('--delete-',delete_algorithm,' ')" -b \
				-b \
				-i "count(quiet) > 0" -o "--quiet " -b \
				-i "count(perms) > 0" -o "--perms " -b \
				-i "count(xattrs) > 0" -o "--xattrs " -b \
				-i "string-length(extraoptions) > 0" -v "concat(extraoptions,' ')" -b \
			-b \
			-v "concat('\"',source,'\" \"',destination,'\"')" -n \
			-o "/bin/rm -f ${_rsyncflag}" -n \
			-v "concat('/usr/bin/logger -p local4.notice \"End of local RSYNC synchronization from ',source,' to ',destination,'\"')" \
			${configxml_file} | /usr/local/bin/xml unesc > "${_rsyncscript}"

		# Set owner and execute rights of the script
		/usr/sbin/chown ${_who} "${_rsyncscript}"
		/bin/chmod 0770 "${_rsyncscript}"

		_scriptnum=$(( ${_scriptnum} - 1 ))
	done
fi

# Set log file permissions
if [ ! -e "${rsync_local_logfile}" ]; then
	cat /dev/null > "${rsync_local_logfile}"
fi
/bin/chmod ${rsync_local_logfile_mode} "${rsync_local_logfile}"
