#!/bin/sh
#
# FreeBSD History: src/etc/rc.d/nfslocking,v 1.11 2004/10/07 13:55:26 mtm Exp
# $FreeBSD: src/etc/rc.d/statd,v 1.22.2.1.2.1 2011/11/11 04:20:22 kensmith Exp $
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2014 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (c) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# All rights reserved.
#
# Changes:	- Remove nfsserver nfsclient
#

# PROVIDE: statd
# REQUIRE: nfsd rpcbind
# BEFORE:  DAEMON
# KEYWORD: nojail shutdown
# XQUERY: -i "count(//nfsd/enable) > 0" -o "0" -b
# RCVAR: rpc_statd nfs_server

. /etc/rc.subr

name="statd"
rcvar=rpc_statd_enable
command="/usr/sbin/rpc.${name}"
start_precmd='statd_precmd'
stop_precmd='checkyesno nfs_server_enable || checkyesno nfs_client_enable'
status_precmd=$stop_precmd

# Make sure that we are either an NFS client or server, and that we get
# the correct flags from rc.conf(5).
#
statd_precmd()
{
	local ret
	ret=0

	if ! checkyesno nfs_server_enable && ! checkyesno nfs_client_enable
	then
		ret=1
	fi
	if ! checkyesno rpcbind_enable && \
	    ! /etc/rc.d/rpcbind forcestatus 1>/dev/null 2>&1
	then
		force_depend rpcbind || ret=1
	fi
	rc_flags=${rpc_statd_flags}
	return ${ret}
}

load_rc_config $name
run_rc_command $1
