#!/bin/sh
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2014 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (c) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# All rights reserved.
#

# PROVIDE: htpasswd
# REQUIRE: cleanvar

. /etc/rc.subr
. /etc/configxml.subr

# Defaults
htpasswd=${htpasswd:-"/var/run/.htpasswd"}

echo "Generating .htpasswd."

# Encrypt password
_password=`configxml_get "//system/password"`
_password_md5=`/usr/sbin/mkpw -e md5 "${_password}"`

# Generate the /var/run/.htpasswd file used by lighttpd
/usr/local/bin/xml sel -t \
	-i "string-length(//system/username) > 0" -v //system/username -b \
	-i "string-length(//system/username) = 0" -o "admin" -b \
	-o ":${_password_md5}" \
	${configxml_file} | /usr/local/bin/xml unesc > ${htpasswd}

/bin/chmod 0600 ${htpasswd}
