#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/DAEMON,v 1.6.4.1.2.1 2011/11/11 04:20:22 kensmith Exp $
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2014 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (c) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# All rights reserved.
#

# PROVIDE: DAEMON
# REQUIRE: NETWORKING SERVERS CONFIG

#	This is a dummy dependency, to ensure that general purpose daemons
#	are run _after_ the above are.
