#!/bin/sh
#
# $FreeBSD: stable/9/etc/rc.d/nfsd 223847 2011-07-07 20:59:42Z rmacklem $
#
# Part of NAS4Free (http://www.nas4free.org).
# Copyright (c) 2012-2014 The NAS4Free Project <info@nas4free.org>.
# All rights reserved.
#
# Portions of freenas (http://www.freenas.org).
# Copyright (c) 2005-2011 Olivier Cochard-Labbe <olivier@freenas.org>.
# All rights reserved.
#

# PROVIDE: nfsd
# REQUIRE: mountd hostname gssd nfsuserd
# KEYWORD: nojail shutdown
# XQUERY: -i "count(//nfsd/enable) > 0" -o "0" -b
# RCVAR: nfs_server

. /etc/rc.subr
. /etc/configxml.subr

name="nfsd"
rcvar=nfs_server_enable
command="/usr/sbin/${name}"

# Customize number of server processes/daemons
nfs_server_flags=`/usr/local/bin/xml sel -t -v "concat('-u -t -n ',//nfsd/numproc)" ${configxml_file} | /usr/local/bin/xml unesc`

load_rc_config $name
start_precmd="nfsd_precmd"
sig_stop="USR1"

nfsd_precmd()
{
	if checkyesno oldnfs_server_enable; then
		rc_flags="-o ${nfs_server_flags}"

		# Load the module now, so that the vfs.nfsrv sysctl
		# oids are available.
		load_kld nfsserver

		if checkyesno nfs_reserved_port_only; then
			echo 'NFS on reserved port only=YES'
			/sbin/sysctl vfs.nfsrv.nfs_privport=1 > /dev/null
		fi
	else
		rc_flags="${nfs_server_flags}"

		# Load the modules now, so that the vfs.nfsd sysctl
		# oids are available.
		load_kld nfsd

		if checkyesno nfs_reserved_port_only; then
			echo 'NFS on reserved port only=YES'
			/sbin/sysctl vfs.nfsd.nfs_privport=1 > /dev/null
		fi

		if checkyesno nfsv4_server_enable; then
			if ! checkyesno nfsuserd_enable  && \
			    ! /etc/rc.d/nfsuserd forcestatus 1>/dev/null 2>&1
			then
				if ! force_depend nfsuserd; then
					err 1 "Cannot run nfsuserd"
				fi
			fi
		else
			echo 'NFSv4 is disabled'
			/sbin/sysctl vfs.nfsd.server_max_nfsvers=3 > /dev/null
		fi
	fi

	if ! checkyesno rpcbind_enable  && \
	    ! /etc/rc.d/rpcbind forcestatus 1>/dev/null 2>&1
	then
		force_depend rpcbind || return 1
	fi

	if ! checkyesno mountd_enable  && \
	    ! /etc/rc.d/mountd forcestatus 1>/dev/null 2>&1
	then
		force_depend mountd || return 1
	fi
	return 0
}

run_rc_command "$1"
